시작 부분의 공백을 허용해도 괜찮지 않을까요?
rycont/umjunsik-lang pull request #18
Opened 2021-04-27 07:49 UTC by Ign0reLee

안녕하세요, python으로 재미삼아 작성하고 있었는데, 틀린 부분이 없어 보였는데 계속 엄랭이냐 에러가 발생해서, 찾아보니 "어떻게"부분에서 공백을 허용하지 않더라고요.

맨 마지막 줄의 이 사람이름이냐!의 경우 형식을 완벽히 지키는게 타당해보이지만, 어떻게의 경우는 어떻게 앞 뒤로의 공백이 얼마나 있던 인식할 수 있으면 좋을 것 같아서요.

replace를 활용하여 수정해보았습니다.

감사합니다

2021-04-27 08:18 UTC, Ign0reLee commented
최근 수정 부분은 단순 replace로 공백을 지우면 의도한 " 어떻게 "뿐만아니라 "어 떻게"등도 가능하게되서, 교차 검증을 위해 넣었습니다.
어떻게라고 정확하게 작성은 하되, 어떻게의 앞뒤 공백은 허용하도록 수정했습니다.

또 생각해보니 파이썬 말고 다른 언어들은 어떻게 작성되어있는지 체크를 안한 문제도 있네요.

감사합니다.

2021-04-30 11:04 UTC, rycont requested changes
의견 고맙습니다! 코멘트 남겨주신것처럼 "어떻게"의 앞 뒤에 공백이 있는 경우에 대해 생각을 해보았으나, 뒤에 들어가는 공백은 허용하고(✔️`어떻게 `), 앞에 들어가는 공백은 허용하지 않는(❌` 어떻게`) 편이 코드의 일관성을 유지하는데 도움이 될 것 같습니다.

2021-04-30 11:05 UTC, rycont commented on umjunsik-lang-python/runtime.py
> +        if check and (code[0].replace(" ","") != '어떻게' or code[-1] != '이 사람이름이냐!' or not '어떻게' in code[0]) :
- "어떻게"의 앞에 오는 공백은 기존처럼 에러를 띄우게 수정

2021-04-30 16:50 UTC, Ign0reLee commented
안녕하세요, 답변 주셔서 감사합니다.

말씀하신대로 "어떻게"의 앞쪽 부분의 공백을 비허용하도록 코드를 수정하던 중, 기존 코드자체가 앞쪽의 공백을 허용한다는 것을 깨달았습니다.

원인은 split을 하면서strip()을 사용하는데, 이로인해 전체 문장의 앞 뒤의 공백을 전부 삭제하게되고,
code[0]에는 앞쪽 공백이 전부 삭제되어 들어가는 것 같습니다.

따라서 해당 부분의 strip을 rstrip()으로 대체하여 오른쪽 끝 부분만 제거하였고, startwith명령어로 시작을 어떻게 형식으로 시작 할 경우에만 코드가 돌아가도록 수정완료하였습니다.

따라서 이 코드는, "어떻게(뒤쪽 공백은 허용)"으로 시작하고, "이 사람이름이냐!(뒤쪽 공백 허용)"의 형태로 이루어져 있습니다.

그 외에 혹시 리드미 부분의 문법과, example로 만드신 문법이 조금 차이가 나는 부분이 있는데, 해당 부분은 이번 풀리퀘가 끝나면 따로 진행하겠습니다.

내용은 python umlang의 경우에, 마지막 문장이 "이 사람이름이냐!"로 끝나게 되어있지만, readme나, 몇개의 example에서는 "이 사람이름이냐 ㅋㅋ"로 이루어져있습니다.

감사합니다.

2021-04-30 22:15 UTC, rycont commented
런타임에 대한 깊은 리서치 고맙습니다. 보내주신 변경사항은 메인브랜치에 반영하겠습니다!

2021-04-30 22:16 UTC, rycont commented
@all-contributors please add @Ign0reLee for code

2021-04-30 22:17 UTC, merged